<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$params = $this->item->params;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

?>
<div class="col-6 col-sm-3 col-lg-2 project-container">

<!-- Image -->
<a class="img-link" href="<?php echo JLayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); //Using the item title to store the href ?>" target="_blank">
	<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
</a>

<!--Intro Text-->
<div class="row-introtext"><?php echo $this->item->introtext; ?></div>

<!--Tags-->
<?php if (!empty($this->item->tags->itemTags)) : ?>
	<?php echo JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
<?php //echo $this->item->event->beforeDisplayContent; ?>
</div>
